# Generated by Django 2.2.9 on 2020-01-17 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_publish',
            field=models.BooleanField(default=False),
        ),
    ]
