# Generated by Django 2.2.9 on 2020-01-17 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_is_publish'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='is_publish',
        ),
    ]
