# Generated by Django 2.2.9 on 2020-01-20 13:43

from django.db import migrations, models
import practice.utils


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20200120_2158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='photo',
            field=models.ImageField(upload_to=practice.utils.uuid_upload_to),
        ),
    ]
