# Generated by Django 2.2.9 on 2020-01-20 13:43

from django.db import migrations, models
import practice.utils


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_item_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='photo',
            field=models.ImageField(blank=True, upload_to=practice.utils.uuid_upload_to),
        ),
    ]
